name: first-workflow
on: [push]

jobs:
  shell-cmd-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Hello
        run: echo "Hello Wold"
      - name: multiple line cmd
        run: |
          node -v
          npm -v
